<?php

namespace Zethzer\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function getNews($page, $nbPerPage){
		if ((int) $page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur Ã  1 (valeur : "'.$page.'").');
		}

		$query=$this->createQueryBuilder('n')
					->leftJoin('n.image', 'i')
					->addSelect('i')
					->where('n.type=0')
					->orWhere('n.type=2')
					->orderBy('n.date', 'DESC')
					->getQuery();

		$query->setFirstResult(($page-1) * $nbPerPage)
			  ->setMaxResults($nbPerPage);

		return new Paginator($query);
	}

	public function getNewsSlide(){
		$query=$this->createQueryBuilder('n')
					->leftJoin('n.image', 'i')
					->addSelect('i')
					->where('n.type=1')
					->orderBy('n.date', 'DESC')
					->getQuery();

		return $query->setMaxResults(4)->getResult();
	}

	public function getNewsImportant(){
		$query=$this->createQueryBuilder('n')
					->leftJoin('n.image', 'i')
					->addSelect('i')
					->where('n.type=2')
					->orderBy('n.date', 'DESC')
					->getQuery();

		return $query->setMaxResults(2)->getResult();
	}
}
