ZethzerContestBundle:
    resource: "@ZethzerContestBundle/Resources/config/routing.yml"
    prefix:   /main

ZethzerServerManagementBundle:
    resource: "@ZethzerServerManagementBundle/Resources/config/routing.yml"
    prefix:   /main

ZethzerForumBundle:
    resource: "@ZethzerForumBundle/Resources/config/routing.yml"
    prefix:   /main

ZethzerNewsBundle:
    resource: "@ZethzerNewsBundle/Resources/config/routing.yml"
    prefix: /main

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /main/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /main/inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /main/reinitialisation

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /main/profile