parameters:
#    zethzer_forum.example.class: Zethzer\ForumBundle\Example

services:
#    zethzer_forum.example:
#        class: %zethzer_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
