parameters:
#    zethzer_contest.example.class: Zethzer\ContestBundle\Example

services:
#    zethzer_contest.example:
#        class: %zethzer_contest.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
